# Generated by Django 4.2.7 on 2023-11-30 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='dictionary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='metadata.dictionary', verbose_name='справочник'),
        ),
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.CharField(choices=[('text', 'Простой текст без ограничений'), ('cyrillic', 'Только кириллица'), ('int', 'Целое число'), ('bigint', 'Большое целое число'), ('real', 'Дробное число'), ('dict', 'Справочное значение')], max_length=15, verbose_name='тип поля'),
        ),
    ]
