# Generated by Django 4.2.7 on 2023-12-01 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FindField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.PositiveSmallIntegerField(default=0, verbose_name='№')),
                ('title', models.CharField(max_length=200, verbose_name='наименование')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='find_fields', to='metadata.field', verbose_name='поле')),
            ],
            options={
                'verbose_name': ('поле для поиска',),
                'verbose_name_plural': 'поля для поиска',
                'ordering': ('-pos',),
            },
        ),
    ]
