# Generated by Django 4.2.7 on 2023-11-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0002_field_dictionary_alter_field_field_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='активный')),
                ('old_id', models.BigIntegerField(blank=True, null=True, verbose_name='old_id')),
                ('date_start', models.DateTimeField(blank=True, null=True, verbose_name='дата начало')),
                ('date_end', models.DateTimeField(blank=True, null=True, verbose_name='дата конец')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('created_user', models.CharField(max_length=150, verbose_name='кем создан')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='изменен')),
                ('changed_user', models.CharField(max_length=150, verbose_name='кем изменен')),
            ],
            options={
                'verbose_name': ('документ',),
                'verbose_name_plural': 'документы',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterField(
            model_name='converter',
            name='num',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='№'),
        ),
        migrations.AlterField(
            model_name='database',
            name='num',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='№'),
        ),
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.CharField(choices=[('text', 'Простой текст без ограничений'), ('cyrillic', 'Только кириллица'), ('int', 'Целое число'), ('bigint', 'Большое целое число'), ('numeric', 'Дробное число'), ('dict', 'Справочное значение'), ('date', 'Дата'), ('time', 'Время'), ('timestamp', 'Дата и время')], max_length=15, verbose_name='тип поля'),
        ),
        migrations.AlterField(
            model_name='field',
            name='num',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='№'),
        ),
        migrations.AlterField(
            model_name='form',
            name='num',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='№'),
        ),
        migrations.AlterField(
            model_name='group',
            name='num',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='№'),
        ),
        migrations.AlterField(
            model_name='report',
            name='num',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='№'),
        ),
    ]
