# Generated by Django 4.2.7 on 2023-11-30 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0003_document_alter_converter_num_alter_database_num_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
