# Generated by Django 4.2.7 on 2023-12-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lst', models.SmallIntegerField()),
                ('punkt', models.CharField(blank=True, max_length=150, null=True)),
                ('raion', models.CharField(blank=True, max_length=150, null=True)),
                ('obl', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asb',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lst', models.SmallIntegerField()),
                ('obl', models.BigIntegerField(blank=True, null=True)),
                ('dr', models.DateField(blank=True, null=True)),
                ('ot', models.CharField(blank=True, max_length=50, null=True)),
                ('im', models.CharField(blank=True, max_length=50, null=True)),
                ('fam', models.CharField(blank=True, max_length=50, null=True)),
                ('iin', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField()),
                ('old_id', models.BigIntegerField(blank=True, null=True)),
                ('date_start', models.DateTimeField(blank=True, null=True)),
                ('date_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('created_user', models.CharField(max_length=150)),
                ('changed_at', models.DateTimeField()),
                ('changed_user', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'documents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('is_enable', models.BooleanField()),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
    ]
