# Generated by Django 4.2.7 on 2023-11-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asb',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lst', models.SmallIntegerField()),
                ('vt', models.TimeField(blank=True, null=True)),
                ('dt', models.DateField(blank=True, null=True)),
                ('p1', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('country', models.BigIntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('im', models.CharField(blank=True, max_length=50, null=True)),
                ('fam', models.CharField(blank=True, max_length=35, null=True)),
            ],
            options={
                'db_table': 'asb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('is_enable', models.BooleanField()),
            ],
            options={
                'db_table': 'country',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField()),
                ('old_id', models.BigIntegerField(blank=True, null=True)),
                ('date_start', models.DateTimeField(blank=True, null=True)),
                ('date_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('created_user', models.CharField(max_length=150)),
                ('changed_at', models.DateTimeField()),
                ('changed_user', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'documents',
                'managed': False,
            },
        ),
    ]
