# Generated by Django 5.0 on 2024-01-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lst', models.SmallIntegerField()),
                ('region', models.CharField(blank=True, max_length=150, null=True)),
                ('district', models.CharField(blank=True, max_length=150, null=True)),
                ('punkt', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.BigIntegerField(blank=True, null=True)),
                ('registration_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asb',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lst', models.SmallIntegerField()),
                ('surname', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('patronymic', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('iin', models.BigIntegerField(blank=True, null=True)),
                ('citizen', models.BigIntegerField(blank=True, null=True)),
                ('nation', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('is_enable', models.BooleanField()),
            ],
            options={
                'db_table': 'countries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField()),
                ('old_id', models.BigIntegerField(blank=True, null=True)),
                ('date_start', models.DateTimeField(blank=True, null=True)),
                ('date_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('created_user', models.CharField(max_length=150)),
                ('changed_at', models.DateTimeField()),
                ('changed_user', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'documents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nationals',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('is_enable', models.BooleanField()),
            ],
            options={
                'db_table': 'nationals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Registrationstate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('is_enable', models.BooleanField()),
            ],
            options={
                'db_table': 'registrationstate',
                'managed': False,
            },
        ),
    ]
