# Generated by Django 4.2.7 on 2023-12-13 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='asb',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='documents',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'managed': True},
        ),
    ]
