# Generated by Django 5.0 on 2024-01-01 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='asb',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='countries',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='documents',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='nationals',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='registrationstate',
            options={'managed': True},
        ),
    ]
