# Generated by Django 5.0.1 on 2024-01-04 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='наименование')),
            ],
            options={
                'verbose_name': 'роль',
                'verbose_name_plural': 'роли',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='логин')),
                ('first_name', models.CharField(max_length=150, verbose_name='имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='фамилия')),
                ('middle_name', models.CharField(max_length=150, verbose_name='отчество')),
                ('is_active', models.BooleanField(default=True, verbose_name='активный')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='администратор')),
                ('is_staff', models.BooleanField(default=False, verbose_name='штатный сотрудник')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='изменен')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='metadata.department', verbose_name='подразделение')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FormAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(blank=True, choices=[('read', 'чтение'), ('write', 'запись'), ('delete', 'удаление')], max_length=10, null=True, verbose_name='тип доступа')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='metadata.form', verbose_name='форма')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='auths.role', verbose_name='роль')),
            ],
            options={
                'verbose_name': 'доступ к формам',
                'verbose_name_plural': 'доступ к формам',
                'ordering': ('role',),
            },
        ),
        migrations.CreateModel(
            name='DatabaseAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='metadata.database', verbose_name='база данных')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='auths.role', verbose_name='роль')),
            ],
            options={
                'verbose_name': 'доступ к БД',
                'verbose_name_plural': 'доступ к БД',
                'ordering': ('role',),
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='auths.role', verbose_name='роль')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'роли пользователя',
                'verbose_name_plural': 'роли пользователей',
                'ordering': ('user', 'role'),
            },
        ),
    ]
